export const data = [
  {
    id: 1,
    name: 'Channel',
    image: require ('../assets/product-6.png'),
    desc: 'Fit and Flare',
    price: 120.99,
    promo: '10% off',
  },
  {
    id: 2,
    name: 'Victoria',
    image: require ('../assets/product-5.png'),
    desc: 'Empire Dress',
    price: '136.00',
    promo: '',
  },
  {
    id: 3,
    name: 'Zara',
    image: require ('../assets/product-4.png'),
    desc: 'Summer Vibes',
    price: 120.99,
    promo: '',
  },
  {
    id: 4,
    name: 'Harbour',
    image: require ('../assets/product-3.png'),
    desc: 'Fit and Flare',
    price: 120.99,
    promo: '20% off',
  },
  {
    id: 5,
    name: 'Channel',
    image: require ('../assets/product-2.png'),
    desc: 'Fit and Flare',
    price: 120.99,
    promo: '10% off',
  },
  {
    id: 6,
    name: 'Victoria',
    image: require ('../assets/product-1.png'),
    desc: 'Fit and Flare',
    price: 120.99,
    promo: '10% off',
  },
];
